MovieShopMVC/Controllers/MovieController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        // showing details of the movie
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }

        public async Task<IActionResult> Genre(int id, int pageSize = 30, int pageNumber = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedMovies", pagedMovies);
        }
    }
}

MovieShopMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        // all these action methods should only be execute when user is loged in

        private readonly ICurrentLoggedInUser _currentLogedInUser;
        public UserController(ICurrentLoggedInUser currentLogedInUser)
        {
            _currentLogedInUser = currentLogedInUser;
        }

        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            // go to database and get all the movies purchased by user, user id
            // var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];
            // can create a class the exposes HttpContext cooke decrypted info and claims
            var userId = _currentLogedInUser.UserId;
            // use the UserId and send to User Serivce to get information for that User 
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddReview()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddFavorite()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BuyMovie()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            return View();
        }
    }
}

MovieShopMVC/Views/Shared/Components/Genre/GenreViewComponent.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Views.Shared.Components.Genre
{
    public class GenreViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenreViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }
    }
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu">
                                @*call the Genre view component *@
                                @await Component.InvokeAsync("Genre")
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginInfo"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_LoginInfo.cshtml
@using MovieShopMVC.Services


 @inject ICurrentLoggedInUser currentUser

 @if (currentUser.IsAuthenticated)
 {
     @* Hide login and Register button if user is Authenticated and show USer;s Full Name, Email and links
        for Logout and VIew Profile Pages *@

    <div class="text-end" >
        <ul class="nav">
            <li class="nav-item dropdown text-capitalize"> 
                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropDownProfile" data-bs-toggle="dropdown">  
                    @currentUser.FullName
                </a>

                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="User" asp-action="Purchases"> Purchases </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Favorites"> Favorites </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Profile"> View Profile/Account </a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout"> Logout </a>
                </div>
            </li>
        </ul>
    </div>

 }
else
{
    @* Show Login and Register buttons if User is not Authenticated
     use this partial view inside the layout Page*@
     
    <div class="text-end">
       <a class="btn btn-outline-dark me-2" asp-controller="Account" asp-action="Login" > Login </a>
       <a class="btn btn-outline-dark me-2" asp-controller="Account" asp-action="Register" > Register </a>
    </div>
}

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@*Movie Card Partial View will be used across multiple views in our application*@

@model ApplicationCore.Models.MovieCardModel

<div class="card mb-4 shadow">
    <a asp-controller="Movie" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>