MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var cast = await _castService.GetCastDetails(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/MovieController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        // showing details of the movie
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }

        public async Task<IActionResult> Genre(int id, int pageSize = 30, int pageNumber = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedMovies", pagedMovies);
        }
    }
}

MovieShopMVC/Views/Movie/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel

<div class="container-fluid">
    <div class="row p-3" style="background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),url(@Model.BackdropUrl)">
        <div class="col-4">
            <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />  
        </div>
        <div class="col-5 text-light">
            <h2> @Model.Title </h2>
            <p> @Model.Tagline </p>
            <p class="nowrap">
                <span>@Model.RunTime m | @Model.ReleaseDate.Value.Year &nbsp;</span>
                @foreach (var genre in Model.Genres) 
                {
                    <span class="badge bg-secondary nowrap" style="mix-blend-mode: difference;"> @genre.Name</span>
                }
            </p>
            <h4 class="badge bg-success">@Model.Rating</h4>
            <p>@Model.Overview</p>
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#reviewModal">
                <span class="fa fa-pencil-square fa-fw"></span>Review
            </button>
            <div class="modal" id="reviewModal" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                               <h5 class="modal-title">Leave a review</h5>
                               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="mb-3 stars">
                                    <input class="btn btn-outline-secondary" id="star-5" type="radio" name="star"/>
                                    <label for="star-5">1</label>
                                    <input class="btn btn-outline-secondary" id="star-4" type="radio" name="star"/>
                                    <label for="star-4">2</label>
                                    <input class="btn btn-outline-secondary" id="star-3" type="radio" name="star"/>
                                    <label for="star-3">3</label>
                                    <input class="btn btn-outline-secondary" id="star-2" type="radio" name="star"/>
                                    <label for="star-2">4</label>
                                    <input class="btn btn-outline-secondary" id="star-1" type="radio" name="star"/>
                                    <label for="star-1">5</label>
                                </div>
                                <div class="mb-3">
                                    <label for="message-text" class="col-form-label">Review:</label>
                                    <textarea class="form-control" id="message-text"></textarea>
                                </div>
                            </form>                              
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-dark">Save review</button>
                        </div>
                    </div>
                 </div>
            </div>
            <br />
            <br /> 
            <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#buyMovieModal">
                Buy $@Model.Price
            </button>
            <div class="modal" id="buyMovieModal" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                               <h5 class="modal-title">Confirm purchase</h5>
                               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="mb-3">
                                    <p>Purchase @Model.Title for @Model.Price ?</p>
                                </div>
                            </form>                              
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-dark">Purchase</button>
                        </div>
                    </div>
                 </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-5">
            <h4>Movie Facts</h4>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <span class="fa fa-calendar fa-fw"></span> Release Date
                    <span class="badge bg-secondary rounded-pill">@Model.ReleaseDate.Value.ToString("D").Replace(Model.ReleaseDate.Value.DayOfWeek.ToString()+ ", ", "")</span>
                </li>
                <li class="list-group-item">
                    <span class="fa fa-hourglass fa-fw" aria-hidden="true"></span> Runtime
                    <span class="badge bg-secondary rounded-pill">@Model.RunTime m</span>
                </li>
                <li class="list-group-item">
                    <span class="fa fa-money fa-fw"></span> Box Office
                    <span class="badge bg-secondary rounded-pill">$@string.Format("{0:0,0.00}", Model.Revenue)</span>
                </li>
                <li class="list-group-item">
                    <span class="fa fa-usd fa-fw"></span> Budget
                    <span class="badge bg-secondary rounded-pill">$@string.Format("{0:0,0.00}", Model.Budget)</span>
                </li>
            </ul>
            <h4>Trailers</h4>
            <ul class="list-group list-group-flush">
                @foreach (var trailer in Model.Trailers) 
                {
                    <li class="list-group-item">
                        <span class="fa fa-youtube-play fa-fw"></span>
                        <a href="@trailer.TrailerUrl">
                             @trailer.Name
                        </a>
                    </li>
                }
            </ul>
        </div>
        <div class="col-7">
            <h4>Cast</h4>
            <div class="list-group list-group-flush">
                @foreach (var cast in Model.Casts)
                {
                    <a class="list-group-item text-decoration-none flex-nowrap" asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id">
                        <img class="col-1 rounded-circle float-start" src="@cast.ProfilePath" alt="Cast member portrait">
                        <span class="col-1 float-start">&nbsp;</span>
                        <span class="col-4 float-start">@cast.Name</span>
                        <span class="col-1 float-start">&nbsp;</span>
                        <span class="col-5 float-start">@cast.Character</span>
                    </a>        
                }
            </div>
        </div>
    </div>
</div>

MovieShopMVC/Views/Movie/PagedMovies.cshtml
@model ApplicationCore.Models.PagedResultSetModel<ApplicationCore.Models.MovieCardModel>

<div class="rounded">
    <div class="container bg-light">
        <div class="row">
            @foreach (var movie in Model.PagedData)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    <partial name="_MovieCard" model="movie" />
                </div>
            }
        </div>
    </div>
</div>

@*Display previous and Next Buttons
  When you are on first Page Previous button should be disabled
  When you are on last page Next button should be disabled *@

@{
    var previousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a class="btn btn-dark @previousDisabled" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber-1)">
    Previous
</a>

<a class="btn btn-dark @nextDisabled" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber + 1)">
    Next
</a>